### ISSUE TITLE
#8 Display 50 Hero by page

### ISSUE THREAD

**Issue by samah7** [samah7/TheGameApp#8]

**Comment by MONSEFOT** [comment]
T

**Comment by MONSEFOT** [comment]
This task is very easy , 

> **First** : In the sever-side :`

- @linam2021  you ' ll just edit the function which brings the data you ll add a _start Index_ which the api start countering from it 

> **Second** : In the client side : 

 

- you ll edit your code lie this : 

`The Code :
     
    Future<List<AnimeForList>> _fetchingAnimes(int startIndex ) async {
       List<AnimeForList> animes = [];
    //getting animes data from the api you have to select the starting index of the proccess in api
    final response = await ApiRequest().get(ApiURLs().get_anime_url + '?page[offset]=$startIndex');

    //when the proccess is done you will get an api response with the data list
    if (response != null) {
      //transforming the json data to and a list of animes and returning it
      for (Map<String, dynamic> anime in response['data']) {
        animes.add(
          AnimeForList(
            id: int.parse(anime['id']),
            title: anime['attributes']['titles']['en_jp'],
            coverImage: (anime['attributes']['coverImage'] != null)
                ? anime['attributes']['coverImage']['large']
                : null,
            posterImage: (anime['attributes']['posterImage'] != null)
                ? anime['attributes']['posterImage']['tiny']
                : null,
            status: anime['attributes']['status'],
            episodeCount: anime['attributes']['episodeCount'],
            averageRating: anime['attributes']['averageRating'],
          ),
        );
      }
      return animes;
    } else {
      throw Exception('error fetching posts');
    }
  }`

> And This is the whole [source](https://github.com/MONSEFOT/MyMission-API/blob/main/app/Http/Controllers/api/UserController.php)

**Comment by linam2021** [comment]
@MONSEFOT 
OK .. I'll edit the function in the api

**Comment by zahoramouss** [comment]
hi @MONSEFOT i found solution by using a listener
but i got troubles with the fuction of fetch points and am trying to fix it

**Comment by MONSEFOT** [comment]
@zahoramouss  ok sis you can share with us your problem and we can help you , share with us your code problem

**Comment by zahoramouss** [comment]
@MONSEFOT  
sorry i didn't see you mesage i fix the the problem and  i make pagination 
there is a problem with from json i will load the pagination today i try to fix that then thank you
